<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FunctionLibraryLegacy</RootNamespace>
	<TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Mindbox.Data.Linq" Version="10.8.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{3259aa49-8aa1-44d3-9025-a0b520596a8c}" />
  </ItemGroup>
</Project>